### ISSUE TITLE
Configuration dialog goes off screen (buttons unclickable)

### ISSUE THREAD

**Issue by ghost** [Jellby/PrincePDF#1]
As you can see from the screenshot, the configuration dialog has borders that goes off screen.
The "OK" button is not clickable.
Also, the dialog is not resizable (going with the mouse on the border and trying to reset it does not work as expected)

![prince_pdf_plugin_config_dlg](https://user-images.githubusercontent.com/1469713/35914250-e22633bc-0c02-11e8-8325-d2acd9e94276.png)

**Comment by Jellby** [comment]
Hmm... I'd blame Qt for this. Maybe there's something I can do (or I'm doing wrong), I'll check that, but it may be a Windows issue, and I can't try on Windows. On my computer I can Alt-drag to move the windows (clicking anywhere, not just on the title bar), this would be a workaround.

**Comment by ghost** [comment]
It cannot be dragged like that.
The problem is also that the window is unresizable

**Comment by ghost** [comment]
There is an error message in the console when running calibre in debug mode:

> C:\Program Files\Calibre2>calibre-debug.exe -g
> calibre 3.16 [64bit]  embedded-python: True is64bit: True
> Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
> ('Windows', '10', '10.0.16299')
> Python 2.7.12+
> Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
> Interface language: None
> Successfully initialized third party plugins: Prince PDF (1, 4, 2) && Interface Plugin Demo (1, 0, 0)
> Turning on automatic hidpi scaling
> devicePixelRatio: 1.0
> logicalDpi: 96.0 x 96.0
> physicalDpi: 127.664921466 x 127.590697674
> Using calibre Qt style: True
> Starting up...
> Started up in 1.95 seconds with 7 books
> QWindowsWindow::setGeometry: Unable to set geometry 1411x1286+243+115 on QWidgetWindow/'QDialogClassWindow'. Resulting geometry:  1411x1061+243+115 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 432x406, maximum size: 16777215x16777215).

**Comment by ghost** [comment]
I have made a PR to fix the issue
