### ISSUE TITLE
"booktitle" and "chaptertitle" strings are empty

### ISSUE THREAD

**Issue by ghost** [Jellby/PrincePDF#2]
The `booktitle` and `chaptertitle` strings do not work. There is no book title nor chapter title in the top margin. Of course, the book has at least a title in the metadata (I don't know where chapter titles are taken from). Conversely, the `counter(page)` and `counter(pages)` do work. Here is the CSS file:

```
/*
@font-face {
  font-family: serif;
  src: local("Droid Serif")
}
*/

@page {
  size: 210mm 297mm;
  margin: 2.5cm !important;
  @top-left {
    font-size: 50%;
    font-style: italic;
    border-bottom: solid thin black;
    margin-bottom: 1mm;
    content: string(booktitle);
  }
  @top-center {
    font-size: 50%;
    font-style: italic;
    border-bottom: solid thin black;
    margin-bottom: 1mm;
    content: string(chaptertitle);
  }
  @top-right {
    font-size: 50%;
    border-bottom: solid thin black;
    margin-bottom: 1mm;
    content: counter(page) "/" counter(pages);
  }
}

@page:first {
  margin: 1mm 1mm 1mm 1mm;
  @top-left {
    border-width: 0;
    margin: 0;
    content: normal;
  }
  @top-center {
    border-width: 0;
    margin: 0;
    content: normal;
  }
  @top-right {
    border-width: 0;
    margin: 0;
    content: normal;
  }
}

body {
  font-size: 10pt;
  font-family: serif;
  text-align: justify;
  prince-image-resolution: 166dpi;
  hyphens: auto;
  string-set: booktitle "@{@{title}@}@"
  string-set: author "@{@{author}@}@"
}
```

**Comment by Jellby** [comment]
`booktitle` and `chaptertitle` are custom strings that will only work if they are defined. The default stylesheet tries to define `booktitle` using the book's title in the calibre database. Doesn't this work? For the chaptertitle you need some CSS magic (you could check some of my epub books in MobileRead).

**Comment by ghost** [comment]
Yeah, my book has a title on Calibre

**Comment by Jellby** [comment]
It turns out I overlooked the fact that you can't have multiple `string-set` in a selector (and had a syntax mistake too). Just restore the default stylesheet when 1.4.3 shows up or replace:

```
  string-set: booktitle "@{@{title}@}@"
  string-set: author "@{@{author}@}@"
```

with:

```
  string-set: booktitle "@{@{title}@}@" author "@{@{author}@}@";
```
