### ISSUE TITLE
Images are too small

### ISSUE THREAD

**Issue by ghost** [Jellby/PrincePDF#3]
Prince conversion gets images too small, as you can see from this screenshot:

![prince_too_small](https://user-images.githubusercontent.com/1469713/35916513-eae9f508-0c0a-11e8-8ef2-e38d08585f65.png)

Instead, stock PDF conversion scales the images much better

![stock_ok](https://user-images.githubusercontent.com/1469713/35916549-071ca6f8-0c0b-11e8-9b3a-4ca5d80a742e.png)

This is a serious problem because some badly tailored ebooks put text into images which are unreadable if they are too small. Here is an example:

Prince (unreadable):
![passage_a_princeu](https://user-images.githubusercontent.com/1469713/35916694-8c77614e-0c0b-11e8-9c30-effae9c60526.png)

Stock PDF conversion (more readable):
![passage_a_stock](https://user-images.githubusercontent.com/1469713/35916661-6b2f7b70-0c0b-11e8-91c6-b848beac551e.png)

Unless I am missing some Prince option that manages this

**Comment by Jellby** [comment]
Prince should be honoring any CSS applied to the images or using their default resolution. You can try overriding the images resolution with http://www.princexml.com/doc/properties/prince-image-resolution/ or http://www.princexml.com/doc/command-line/#cmd-raster, or add a custom stylesheet that targets the trouble images and sets e.g. `width:100%`. If that doesn't work... try running Prince manually: if it has the same problem it's a Prince bug, not the plugin's.

**Comment by ghost** [comment]
Yeah setting prince-image-resolution solved the issue, thanks!

**Comment by Jellby** [comment]
You can also add a `--css-dpi` command-line argument to your settings or to the specific conversion.
